
# Colors: https://github.com/aaron-williamson/base16-alacritty

[colors]
draw_bold_text_with_bright_colors = false

# TOKYONIGHT ########################################################

[colors.primary]
background = '0x1a1b26'
foreground = '0xa9b1d6'

[colors.cursor]
text = '0x1a1b26'
cursor = '0xa9b1d6'

[colors.normal]
black = '0x1a1b26'
red = '0xc0caf5'
green = '0x9ece6a'
yellow = '0x0db9d7'
blue = '0x2ac3de'
magenta = '0xbb9af7'
cyan = '0xb4f9f8'
white = '0xa9b1d6'

[colors.bright]
black = '0x444b6a'
red = '0xa9b1d6'
green = '0x16161e'
yellow = '0x2f3549'
blue = '0x787c99'
magenta = '0xcbccd1'
cyan = '0xf7768e'
white = '0xd5d6db'

# NORD ##############################################################

#[colors.primary]
#background = '0x2e3440'
#foreground = '0xe5e9f0'
#
#[colors.cursor]
#text = '0x2e3440'
#cursor = '0xe5e9f0'
#
#[colors.normal]
#black = '0x2e3440'
#red = '0xbf616a'
#green = '0xa3be8c'
#yellow = '0xebcb8b'
#blue = '0x81a1c1'
#magenta = '0xb48ead'
#cyan = '0x88c0d0'
#white = '0xe5e9f0'
#
#[colors.bright]
#black = '0x4c566a'
#red = '0xd08770'
#green = '0x3b4252'
#yellow = '0x434c5e'
#blue = '0xd8dee9'
#magenta = '0xeceff4'
#cyan = '0x5e81ac'
#white = '0x8fbcbb'

# GRUVBOX ###########################################################

#[colors.primary]
#background = '0x1d2021'
#foreground = '0xd5c4a1'
#
#[colors.cursor]
#text = '0x1d2021'
#cursor = '0xd5c4a1'
#
#[colors.normal]
#black = '0x1d2021'
#red = '0xfb4934'
#green = '0xb8bb26'
#yellow = '0xfabd2f'
#blue = '0x83a598'
#magenta = '0xd3869b'
#cyan = '0x8ec07c'
#white = '0xd5c4a1'
#
#[colors.bright]
#black = '0x665c54'
#red = '0xfe8019'
#green = '0x3c3836'
#yellow = '0x504945'
#blue = '0xbdae93'
#magenta = '0xebdbb2'
#cyan = '0xd65d0e'
#white = '0xfbf1c7'

#####################################################################

[font]
size = 16.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "None"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "W"
mods = "Command"

[scrolling]
history = 0

[selection]
save_to_clipboard = true

[shell]
args = ["--login"]
program = "/usr/local/bin/bash"

[window]
decorations = "transparent"
opacity = 0.9
startup_mode = "Maximized"

[window.padding]
x = 6
y = 2

