#!/usr/bin/bash

win_id=$1
class=$2
instance=$3

title=$(xtitle "$win_id")

if [[ "$class" = Evilvte || "$class" = Termite ]]; then

    case "$title" in
    work1)
        echo "desktop=8"
        ;;
    work2)
        echo "desktop=9"
        ;;
    esac

elif [[ "$class" = chromium ]]; then

    echo "desktop=1"

    case "$instance" in
    crx_nckgahadagoaajjgafhacjanaoiihapd) # Hangouts
        echo "sticky=on"
        echo "state=floating"
    esac

    case "$title" in
    Untitled)
        echo "state=floating"
        ;;
    esac

elif [[ "$class" = Firefox ]]; then

    echo "desktop=3"

elif [[ "$class" = sun-awt-X11-XFramePeer ||
	"$class" = java-lang-Thread ||
	"$class" = Atasjni ]]; then

    # webex
    echo "state=floating"
    echo "desktop=4"

elif [[ "$class" = Thunderbird || "$class" = "Thunderbird-nightly" ]]; then

    echo "desktop=2"

elif [[ "$class" = Acroread || "$class" = Evince ]]; then

    echo "desktop=3"

elif [[ "$class" = Wfica ]]; then

    echo "desktop=3"

elif [[ "$class" = Pidgin ]]; then

    echo "state=floating desktop=2"

elif [[ "$class" = Gimp ]]; then

    echo "desktop=4"
    echo "follow=on"
    echo "state=floating"

elif [[ "$class" = Wine ]]; then

    echo "desktop=4"
    echo "state=fullscreen"

elif [[ "$class" = Spicy ]]; then

    echo "desktop=4"

elif [[ "$class" = Vncviewer ]]; then

    echo "desktop=5"

elif [[ "$class" = rdesktop ]]; then

    echo "desktop=5"
    # 24px panel + 10px window gap + 5px window border (1890x1026+10+34)
    #echo "state=fullscreen"

elif [[ "$class" = Dunst || "$class" = Gxmessage ]]; then

    echo "sticky=on"
    echo "state=floating"

fi

