#!/usr/bin/bash

bspc config external_rules_command $HOME/.bspwmrc_rules

if [[ -n "$CHROMEBOOK" ]]; then
    bspc config border_width        3
    bspc config window_gap          5
else
    bspc config border_width        5
    bspc config window_gap          10
fi
bspc config split_ratio             0.50
bspc config borderless_monocle      false
bspc config gapless_monocle         true
bspc config focus_by_distance       true
bspc config auto_cancel             true
bspc config ignore_ewmh_focus       true

bspc config focus_follows_pointer   true
bspc config pointer_follows_monitor true
#bspc config pointer_follows_focus   true
bspc config pointer_modifier        mod3

bspc monitor -d 1 2 3 4 5 6 7 8 9 10
if [[ $HOSTNAME = jackshrimp ]]; then
    bspc monitor DVI-I-1 -d 3 4 5 6 7 8 9
    bspc monitor DVI-D-0 -d 1 2 10
    bspc monitor DVI-I-1 -n L
    bspc monitor DVI-D-0 -n R
elif [[ $HOSTNAME = skylark ]]; then
    bspc monitor DVI-I-1 -d 3 4 5 6 7 8 9
    bspc monitor DP-0    -d 1 2 10
    bspc monitor DVI-I-1 -n L
    bspc monitor DP-0    -n R
elif [[ -n "$CHROMEBOOK" ]]; then
    bspc monitor eDP1  -d 1 2 3 4 5 6 7 8 9
    bspc monitor HDMI1 -d 10
    bspc monitor eDP1  -n L
    bspc monitor HDMI1 -n R
fi

bspc config focused_border_color "#ffa500"
bspc config presel_feedback_color "#030303"

pkill -x .bspwm_panel
#pkill -x bspc
$HOME/.bspwm_panel &

