#!/usr/bin/bash

win_id=$1
class=$2
instance=$3

title=$(xtitle "$win_id")

if [[ "$class" = Evilvte || "$class" = Termite ]]; then

    case "$title" in
    work1)
        echo "desktop=8"
        ;;
    work2)
        echo "desktop=9"
        ;;
    esac

elif [[ "$class" = Chromium ]]; then

    echo "desktop=1"

    case "$title" in
    Untitled)
        echo "floating=on"
        ;;
    esac

elif [[ "$class" = Firefox ]]; then

    echo "desktop=2"

elif [[ "$class" = Thunderbird || "$class" = "Thunderbird-nightly" ]]; then

    echo "desktop=2"

elif [[ "$class" = Acroread || "$class" = Evince ]]; then

    echo "desktop=3"

elif [[ "$class" = Pidgin ]]; then

    echo "floating=on desktop=2"

elif [[ "$class" = Gimp ]]; then

    echo "desktop=4"
    echo "follow=on"
    echo "floating=on"

elif [[ "$class" = Wine ]]; then

    echo "desktop=4"
    echo "fullscreen=on"

elif [[ "$class" = Spicy ]]; then

    echo "desktop=4"

elif [[ "$class" = Vncviewer ]]; then

    echo "desktop=5"

elif [[ "$class" = rdesktop ]]; then

    echo "desktop=5"

elif [[ "$class" = Dunst || "$class" = Gxmessage ]]; then

    echo "sticky=on"
    echo "floating=on"

fi

