#!/bin/bash

function hc() { herbstclient "$@"; }

hc emit_hook reload
hc set default_frame_layout 1 # horizontal

Mod=Mod4
hc keyunbind   --all
hc mouseunbind --all
hc unrule      --all

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Shift-o spawn bash -c hclo
hc keybind $Mod-Return  spawn urxvtc
hc keybind $Mod-p       spawn dwm_launch prog
hc keybind $Mod-m       spawn                               \
    /usr/share/doc/herbstluftwm/examples/herbstcommander.sh \
        -fn xft:terminus:bold:size=14                       \
        -nb \#000 -nf \#FA0 -sb \#000 -sf \#0F0

hc keybind $Mod-Up   spawn amixer -q sset Master 1+
hc keybind $Mod-Down spawn amixer -q sset Master 1-

TAG_NAMES=( {1..9} )
TAG_KEYS=( {1..9} 0 )

hc rename default "${TAG_NAMES[0]}" || true
for i in ${!TAG_NAMES[@]} ; do
    hc add "${TAG_NAMES[$i]}"
    key="${TAG_KEYS[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key"       use_index  "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

hc keybind $Mod-period       use_index  +1 --skip-visible
hc keybind $Mod-comma        use_index  -1 --skip-visible
hc keybind $Mod-Shift-period move_index +1 --skip-visible
hc keybind $Mod-Shift-comma  move_index -1 --skip-visible

hc keybind $Mod-r       remove
hc keybind $Mod-space   cycle_layout 1
hc keybind $Mod-u       split vertical 0.5
hc keybind $Mod-o       split horizontal 0.5
hc keybind $Mod-s       floating toggle
hc keybind $Mod-f       fullscreen toggle
hc keybind $Mod-Shift-p pseudotile toggle

RESIZESTEP=0.02
hc keybind $Mod-Control-h resize left  +$RESIZESTEP
hc keybind $Mod-Control-j resize down  +$RESIZESTEP
hc keybind $Mod-Control-k resize up    +$RESIZESTEP
hc keybind $Mod-Control-l resize right +$RESIZESTEP

hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-w           cycle_monitor +1
hc keybind $Mod-e           cycle_monitor -1
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c           cycle
hc keybind $Mod-h           focus left
hc keybind $Mod-j           focus down
hc keybind $Mod-k           focus up
hc keybind $Mod-l           focus right
#hc keybind $Mod-i           jumpto urgent
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

hc set always_show_frame        1
hc set raise_on_click           0 # prevents manage=off clients from being hidden
hc set focus_follows_mouse      1
hc set gapless_grid             0
hc set swap_monitors_to_get_tag 0
hc set smart_frame_surroundings 1
hc set smart_window_borders     0
#hc set tree_style               "*| +`--."
#hc set tree_style               "X|:#+*-."
hc set tree_style               "╾│ ├└╼─┐"

hc set frame_bg_transparent       1
hc set frame_bg_active_color      '#000'
hc set frame_bg_normal_color      '#000'
hc set frame_border_width         2
hc set frame_border_active_color  '#FA0'
hc set frame_border_normal_color  '#000'
hc set window_border_width        1
hc set window_border_active_color '#0F0'
hc set window_border_normal_color '#000'

hc rule                          focus=off # default do not focus new clients
hc rule class=Chromium           tag=1
hc rule class=Firefox            tag=1
hc rule class=Thunderbird        tag=2
hc rule class=Acroread           tag=3
hc rule class=Evince             tag=3
hc rule class=Okular             tag=3
hc rule class=Vncviewer          tag=5
hc rule class=rdesktop           tag=5
hc rule class=Wine               tag=4 fullscreen=on
hc rule class=URxvt title=work1  tag=8 # tmux session work1
hc rule class=URxvt title=work2  tag=9 # tmux session work2
hc rule class=Gxmessage          manage=off

hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
#hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' manage=off
#hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG'                  focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)'     manage=off

if [[ $HOSTNAME = eadmaka ]]; then
    hc remove_monitor 1
    hc move_monitor 0 1920x1080+0+0
    hc add_monitor 1080x1920+1920+0 9
elif [[ $HOSTNAME = jackshrimp ]]; then
    hc remove_monitor 1
    hc move_monitor 0 1680x1050+0+0
    hc add_monitor 1080x1920+1680+0 9
fi

