#!/bin/bash

if [[ -f /etc/bash_completion.d/herbstclient-completion ]]; then
    source /etc/bash_completion.d/herbstclient-completion
fi

# alias hc and add completion for it
function _hc_complete() {
    COMPREPLY=(
        $(herbstclient -q complete "$((COMP_CWORD-1))" "${COMP_WORDS[@]:1}")
    )
}
complete -F _hc_complete hc
alias hc=herbstclient

function hcs() # dump current herbstluftwm settings
{
    for s in `herbstclient complete 1 set`; do
        echo "$s = `herbstclient get $s`"
    done
}

function hc_cur_tag()
{
    herbstclient tag_status | grep -oP "\t#[^\t]*" | cut -b 3
}

function hcl() # dump current herbstluftwm layout for all tags
{
    local TAGC="${1:+`tput setaf 5`}"
    local WINDOWC="${1:+`tput setaf 3`}"
    local TITLEC="${1:+`tput setaf 4`}"
    local CLEAR="${1:+`tput sgr0`}"

    herbstclient complete 1 use |
    while read t; do
        TAG="$t: "
        indent=$(echo -n "$TAG" | sed 's/./ /g')
        TAG="${TAGC}${TAG}${CLEAR}"

        LAYOUT=`herbstclient layout $t`

        echo -e "${TAG}${LAYOUT}" \
            | sed "2,\$ s/^/$indent/" \
            | sed "s/\(0x[0-9a-f]\{1,\}\)/${WINDOWC}\1${CLEAR}/g"

        echo -e "$LAYOUT" | grep -oE "0x[0-9a-f]{1,}" |
        while read w; do
            echo -n "$indent${WINDOWC}$w${CLEAR} - "
            echo    "${TITLEC}`xdotool getwindowname $w`${CLEAR}"
        done
    done
}

function hcosd()
{
    local FGCLR=white
    local OLCLR=blue
    local OUTL=2
    local DELAY=10
    local FONT='-*-terminus-bold-r-*-*-22-*-*-*-*-*-*-*'

    echo -e "$1"                            \
        | osd_cat -A left                   \
                  -i 0                      \
                  -o 30                     \
                  -d $DELAY                 \
                  -O $OUTL                  \
                  -c $FGCLR                 \
                  -u $OLCLR                 \
                  -l `echo -e "$1" | wc -l` \
                  -f $FONT
}

function hclo()
{
    local TS=`herbstclient get tree_style`
    herbstclient set tree_style '*| +`--.'
    local TXT=`hcl`
    herbstclient set tree_style "$TS"
    hcosd "$TXT"
}

function hc_smplayer()
{
    if [[ `herbstclient list_monitors | tail -1 | grep -q "^1"` -eq 1 ]]; then
        notify-send -u critical -a herbstclient "no second monitor"
        return
    fi

    herbstclient focus_monitor 1
    herbstclient use 9

    herbstclient split vertical 0.9
    herbstclient focus down

    herbstclient spawn smplayer
    sleep 2

    herbstclient split horizontal 0.3
    herbstclient focus right

    herbstclient spawn urxvtc
    sleep 2

    herbstclient focus up
    smplayer -send-action open_file
}

