#!/bin/bash

cd notes

hub issue -l High -f "[b]%I[/b]: [b][c=#ff0000]H[/c][/b] %t%n" > /storage/emulated/0/Download/todo_high.txt
hub issue -l Medium -f "[b]%I[/b]: [b][c=#00ff00]M[/c][/b] %t%n" > /storage/emulated/0/Download/todo_medium.txt
hub issue -l Low -f "[b]%I[/b]: [b][c=#0000ff]L[/c][/b] %t%n" > /storage/emulated/0/Download/todo_low.txt

cat /storage/emulated/0/Download/todo_high.txt > /storage/emulated/0/Download/todo.txt
cat /storage/emulated/0/Download/todo_medium.txt >> /storage/emulated/0/Download/todo.txt
cat /storage/emulated/0/Download/todo_low.txt >> /storage/emulated/0/Download/todo.txt

