
# https://starship.rs/config

add_newline = false
format = "$fill$all$directory$character"
c.disabled = true
nodejs.disabled = true
python.disabled = true
lua.disabled = true
ocaml.disabled = true

[fill]
symbol = "."
style = "239"

[directory]
truncation_length = 4
truncation_symbol = "../"
style = "white dimmed"
#format = "[\\[](white dimmed bold) [$path]($style)[$read_only]($read_only_style) [\\]](white dimmed bold) "
format = "[$path]($style)[$read_only]($read_only_style) "

[username]
format = "[$user]($style) "

[hostname]
ssh_only = false
format = "[$hostname]($style) "

[status]
disabled = false

