#!/bin/bash
# $1 is the filename

FNAME="$1"
NFNAME="/tmp/editlabels-`basename "$1"`.$$"

function asklabel() {
    read -e -p "Label ('x' to del) [$2]: " $1
    CVAL=${!1}
}

ACT=`formail -c -X X-Label < "$FNAME"`
asklabel LNAME "`echo $ACT | sed -e 's/^X-Label: //'`"

if [ "$LNAME" ]; then
    if [ "$LNAME" == "x" ]; then
        # label "x" means remove label:
        formail -I "X-Label:" < "$FNAME" > "$NFNAME"
    else
        # set label to new label:
        NEW="X-Label: $LNAME"
        formail -I "$NEW" < "$FNAME" > "$NFNAME"
    fi
fi

# if we created a new file, step over the old one
if [ -f "$NFNAME" ]; then
    mv "$NFNAME" "$FNAME"
fi

exit

