#!/usr/bin/bash

bspc config external_rules_command $HOME/.vnc/vnc_bspwmrc_rules

bspc config border_width            5
bspc config window_gap              10
bspc config split_ratio             0.50
bspc config borderless_monocle      false
bspc config gapless_monocle         true
bspc config focus_by_distance       true
bspc config auto_cancel             true
bspc config ignore_ewmh_focus       true
bspc config focus_follows_pointer   true
bspc config pointer_follows_monitor false

bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc monitor VNC-0 -d 1 2 3 4 5 6 7 8 9 10

bspc rule -a Chromium            desktop=1
bspc rule -a Firefox             desktop=2
bspc rule -a Thunderbird         desktop=2
bspc rule -a Thunderbird-nightly desktop=2
bspc rule -a Acroread            desktop=3
bspc rule -a Evince              desktop=3
bspc rule -a Vncviewer           desktop=5
bspc rule -a Spicy               desktop=5 floating=on
bspc rule -a Wine                desktop=4 fullscreen=on
bspc rule -a Gimp                desktop=4 follow=on floating=on
bspc rule -a Dunst               sticky=on floating=on
bspc rule -a Gxmessage           sticky=on floating=on

bspc config focused_border_color orange

pkill -x vnc_bspwm_panel
#pkill -x bspc
$HOME/.vnc/vnc_bspwm_panel &

