#!/bin/bash

#exec vncserver :13 -PasswordFile ~/.priv/vnc_passwd -bs -ac -nolisten tcp -localhost -dpi 96 -name foobar
exec vncserver :13 -PasswordFile ~/.priv/vnc_passwd -bs -ac -localhost -dpi 96 -name foobar

