#!/bin/bash

#exec vncserver :13 -PasswordFile ~/.priv/vnc_passwd -depth 24 -geometry 1590x990 -alwaysshared -name foobar

# using the following with xrdp
exec vncserver :13 -PasswordFile ~/.priv/vnc_passwd -bs -ac -nolisten tcp -localhost -dpi 96 -name foobar

