#!/bin/bash

xset +fp /usr/share/fonts/100dpi
xset +fp /usr/share/fonts/75dpi
xset +fp /usr/share/fonts/cyrillic
xset +fp /usr/share/fonts/encodings
xset +fp /usr/share/fonts/local
xset +fp /usr/share/fonts/misc
xset +fp /usr/share/fonts/TTF
xset +fp /usr/share/fonts/Type1
xset +fp /usr/share/fonts/util
xset +fp ~/.fonts

xsetroot -solid black
xsetroot -cursor_name left_ptr

xrdb -load $HOME/.Xdefaults

if [[ -n "$VNCDESKTOP" ]]; then
    export XKL_XMODMAP_DISABLE=1
    #vncconfig -nowin &
else # FreeNX
    #setxkbmap -v 10 -geometry "pc(pc105)" -keycodes "evdev+aliases(qwerty)"
    setxkbmap -model us
fi

xmodmap $HOME/.Xmodmap

#[[ -x /usr${LOCAL}/bin/dunst ]] && dunst -config $HOME/.dunstrc &

# fix Java wackiness
[[ -x /usr${LOCAL}/bin/wmname ]] && wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1

#[[ -x /usr${LOCAL}/bin/compton ]] && compton --config $HOME/.comptonrc -f -D 9 --active-opacity 0.9 -i 0.6 -e 0.9 &
[[ -x /usr${LOCAL}/bin/compton ]] && compton --config $HOME/.comptonrc &

termite -c $HOME/.termiterc -e 'bash -li' &

sxhkd -c $HOME/.vnc/vnc_sxhkdrc &
exec /usr/bin/bspwm -c $HOME/.vnc/vnc_bspwmrc

#exec /usr/bin/cwm

#xfce4-terminal -e 'bash -li' &
#exec /usr/bin/startxfce4

