#!/bin/bash

xset +fp /usr/share/fonts/100dpi
xset +fp /usr/share/fonts/75dpi
xset +fp /usr/share/fonts/cyrillic
xset +fp /usr/share/fonts/encodings
xset +fp /usr/share/fonts/local
xset +fp /usr/share/fonts/misc
xset +fp /usr/share/fonts/TTF
xset +fp /usr/share/fonts/Type1
xset +fp /usr/share/fonts/util
xset +fp ~/.fonts

xsetroot -solid black

xrdb -load $HOME/.Xdefaults

if [[ -n "$VNCDESKTOP" ]]; then
    export XKL_XMODMAP_DISABLE=1
    #vncconfig -nowin &
else # FreeNX
    #setxkbmap -v 10 -geometry "pc(pc105)" -keycodes "evdev+aliases(qwerty)"
    setxkbmap -model us
fi

if [[ $HOSTNAME = tiburon ]]; then
    xrandr -s 1600x900
fi

xmodmap $HOME/.Xmodmap

[[ -x /usr${LOCAL}/bin/dunst ]] && dunst -config $HOME/.dunstrc &

#urxvt &

xfce4-terminal -e 'bash -li' &
exec /usr/bin/startxfce4

#evilvte -e bash -li &
#exec /usr/bin/openbox
#exec /usr/bin/pekwm

