
font_size                 15.0
#macos_thicken_font        0.25
modify_font cell_width    -1px
#modify_font cell_height   -1px
text_composition_strategy 1.0 20

startup_session ~/.config/kitty/macos.kitty-session

